In [1]:
import numpy as np
import pandas as pd
df2w =  pd.read_table("./the2w.txt",header=None)
dfall =  pd.read_table("./theall.txt",header=None)
df2w

            0                         1
0          长垣             placanticline
1         长圆孔              slotted hole
2         长圆形                   obround
3        长源分距              long spacing
4       长源距测量  long spacing measurement
...       ...                       ...
20361     座阻尼              site damping
20362     做标记                   marking
20363  做成一式三份                triplicate
20364    做等效层             equivalencing
20365   做空白试验           running a blank

[20366 rows x 2 columns]

In [2]:
dfall

             0                         1
0           长垣             placanticline
1          长圆孔              slotted hole
2          长圆形                   obround
3         长源分距              long spacing
4        长源距测量  long spacing measurement
...        ...                       ...
153733      龟裂          chink ;crocodile
153734    龟裂开始          crack initiation
153735     龟裂的       frustose ;polygonal
153736    昶矫?          coordinate plane
153737  侵薇咴档?               perideltaic

[153738 rows x 2 columns]

In [3]:
df2w.drop_duplicates(subset=0,keep='first',inplace=True)
dfall.drop_duplicates(subset=0,keep='first',inplace=True)
df2w

            0                         1
0          长垣             placanticline
1         长圆孔              slotted hole
2         长圆形                   obround
3        长源分距              long spacing
4       长源距测量  long spacing measurement
...       ...                       ...
20361     座阻尼              site damping
20362     做标记                   marking
20363  做成一式三份                triplicate
20364    做等效层             equivalencing
20365   做空白试验           running a blank

[20342 rows x 2 columns]

In [4]:
dfall

             0                         1
0           长垣             placanticline
1          长圆孔              slotted hole
2          长圆形                   obround
3         长源分距              long spacing
4        长源距测量  long spacing measurement
...        ...                       ...
153733      龟裂          chink ;crocodile
153734    龟裂开始          crack initiation
153735     龟裂的       frustose ;polygonal
153736    昶矫?          coordinate plane
153737  侵薇咴档?               perideltaic

[143739 rows x 2 columns]

In [5]:
df2w.to_csv('./2w20210713.txt', sep='\t', index=False)
dfall.to_csv('./all20210713.txt', sep='\t', index=False)

In [6]:
output = pd.concat([df2w,dfall])
output

             0                         1
0           长垣             placanticline
1          长圆孔              slotted hole
2          长圆形                   obround
3         长源分距              long spacing
4        长源距测量  long spacing measurement
...        ...                       ...
153733      龟裂          chink ;crocodile
153734    龟裂开始          crack initiation
153735     龟裂的       frustose ;polygonal
153736    昶矫?          coordinate plane
153737  侵薇咴档?               perideltaic

[164081 rows x 2 columns]

In [7]:
output.drop_duplicates(subset=0,keep='first',inplace=True)

In [8]:
output

             0                         1
0           长垣             placanticline
1          长圆孔              slotted hole
2          长圆形                   obround
3         长源分距              long spacing
4        长源距测量  long spacing measurement
...        ...                       ...
153733      龟裂          chink ;crocodile
153734    龟裂开始          crack initiation
153735     龟裂的       frustose ;polygonal
153736    昶矫?          coordinate plane
153737  侵薇咴档?               perideltaic

[143739 rows x 2 columns]

In [9]:
output.to_csv('./output20210713.txt', sep='\t', index=False)

In [17]:
import numpy as np
import pandas as pd
alld =  pd.read_table("./oil.txt",header=None)
alld

             0                         1
0           长垣             placanticline
1          长圆孔              slotted hole
2          长圆形                   obround
3         长源分距              long spacing
4        长源距测量  long spacing measurement
...        ...                       ...
174098      龟裂          chink ;crocodile
174099    龟裂开始          crack initiation
174100     龟裂的       frustose ;polygonal
174101    昶矫?          coordinate plane
174102  侵薇咴档?               perideltaic

[174103 rows x 2 columns]

In [72]:
# m,n = alld.shape
# alld.loc[[m-1]][0].values[0]
# c_name = alld[0].values.tolist()
# a= '\ue244昶矫?'
# c_name[-1].encode('utf').decode('unicode_escape')

'î\x90¦ä¾µè\x96\x87å\x92´æ¡£?'

In [5]:
# np.where(alld=='等倍数')

(array([  8731,  29080, 135067], dtype=int64), array([0, 0, 0], dtype=int64))

In [6]:
# alld.loc[[8731,29080, 135067]]

          0             1
8731    等倍数  equimultiple
29080   等倍数  equimultiple
135067  等倍数  equimultiple

In [12]:
alld.drop_duplicates(subset=0,keep='first',inplace=True)

In [13]:
alld.value_counts()

0           1
 GL-l齿轮油    GL-l gear oil                                               1
电气工业        electric industry                                           1
电气体动力学      electrogasdynamics                                          1
电气保护        electric protection                                         1
电气修理        electric repair                                             1
                                                                       ..
尚普兰         champlainian                                                1
尚末          not yet                                                     1
尝尽...的辛酸    drunk to the lees                                           1
尝试          attempt ;had a go at ;smite ;test by trial ;took in hand    1
［钻井船］监控摄象机  rig camera                                                  1
Length: 160158, dtype: int64

In [14]:
alld.to_csv('./allData20210713.txt', sep='\t', index=False)